title: Kyunghee Ko
description: This is a blog of Kyunghee Ko.
show_downloads: false

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://KyungheeKo.github.io" # change this to the base hostname & protocol for your site

remote_theme : lorepirri/cayman-blog

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Kyunghee Ko
image: /thumbnail-jumbo.png
twitter:
  username: 

plugins:
  - jekyll-target-blank
  - jekyll-paginate
  
paginate : 5
paginate_path : "/page:num/"

target-blank:
    rel: nofollow

header_page_refs: #['now', 'about', 'contact']
